psql -U postgres -c 'CREATE DATABASE nat_database;'
psql -U postgres -d nat_database -c 'CREATE TABLE company_clients (company_name TEXT NOT NULL, company_id INT GENERATED ALWAYS AS IDENTITY, tariff TEXT  NOT NULL, PRIMARY KEY (company_id));'
psql -U postgres -d nat_database -c 'CREATE TABLE user_clients (full_name TEXT NOT NULL, home_address TEXT NOT NULL, tariff TEXT NOT NULL, PRIMARY KEY (full_name, home_address));'
psql -U postgres -d nat_database -c 'CREATE TABLE other_providers (asn INTEGER NOT NULL, name TEXT NOT NULL, PRIMARY KEY (asn));'
